/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomPanelTabsTerminalBaseTerminal: typeof import('./src/components/bottomPanel/tabs/terminal/BaseTerminal.vue')['default']
    CommonLanguageSelector: typeof import('./src/components/common/LanguageSelector.vue')['default']
    CommonRefreshButton: typeof import('./src/components/common/RefreshButton.vue')['default']
    CommonStartupDisplay: typeof import('./src/components/common/StartupDisplay.vue')['default']
    CommonUrlInput: typeof import('./src/components/common/UrlInput.vue')['default']
    DesktopDialogView: typeof import('./src/views/DesktopDialogView.vue')['default']
    DesktopStartView: typeof import('./src/views/DesktopStartView.vue')['default']
    DesktopUpdateView: typeof import('./src/views/DesktopUpdateView.vue')['default']
    DownloadGitView: typeof import('./src/views/DownloadGitView.vue')['default']
    InstallDesktopSettingsConfiguration: typeof import('./src/components/install/DesktopSettingsConfiguration.vue')['default']
    InstallGpuPicker: typeof import('./src/components/install/GpuPicker.vue')['default']
    InstallHardwareOption: typeof import('./src/components/install/HardwareOption.vue')['default']
    InstallInstallFooter: typeof import('./src/components/install/InstallFooter.vue')['default']
    InstallInstallLocationPicker: typeof import('./src/components/install/InstallLocationPicker.vue')['default']
    InstallMigrationPicker: typeof import('./src/components/install/MigrationPicker.vue')['default']
    InstallMirrorMirrorItem: typeof import('./src/components/install/mirror/MirrorItem.vue')['default']
    InstallView: typeof import('./src/views/InstallView.vue')['default']
    LayoutsLayoutDefault: typeof import('./src/views/layouts/LayoutDefault.vue')['default']
    MaintenanceStatusTag: typeof import('./src/components/maintenance/StatusTag.vue')['default']
    MaintenanceTaskCard: typeof import('./src/components/maintenance/TaskCard.vue')['default']
    MaintenanceTaskListItem: typeof import('./src/components/maintenance/TaskListItem.vue')['default']
    MaintenanceTaskListPanel: typeof import('./src/components/maintenance/TaskListPanel.vue')['default']
    MaintenanceTaskListStatusIcon: typeof import('./src/components/maintenance/TaskListStatusIcon.vue')['default']
    MaintenanceTerminalOutputDrawer: typeof import('./src/components/maintenance/TerminalOutputDrawer.vue')['default']
    MaintenanceView: typeof import('./src/views/MaintenanceView.vue')['default']
    ManualConfigurationView: typeof import('./src/views/ManualConfigurationView.vue')['default']
    MetricsConsentView: typeof import('./src/views/MetricsConsentView.vue')['default']
    NotSupportedView: typeof import('./src/views/NotSupportedView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerStartView: typeof import('./src/views/ServerStartView.vue')['default']
    TemplatesBaseViewTemplate: typeof import('./src/views/templates/BaseViewTemplate.vue')['default']
    WelcomeView: typeof import('./src/views/WelcomeView.vue')['default']
  }
}
